{
  ["unitframe"] = {
      ["aurawatch"] = {
          ["DRUID"] = {
              [774] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 1,
                      ["g"] = 0.14901961386204,
                      ["r"] = 1,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["xOffset"] = -3,
                  ["yOffset"] = -3,
              },
              [8936] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0.27843138575554,
                      ["g"] = 0.77647066116333,
                      ["r"] = 0.27843138575554,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "LEFT",
                  ["xOffset"] = 15,
                  ["yOffset"] = -1,
              },
              [33763] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0.13333334028721,
                      ["g"] = 0.9215686917305,
                      ["r"] = 0.39607846736908,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "LEFT",
                  ["sizeOffset"] = 9,
                  ["xOffset"] = 3,
                  ["yOffset"] = -1,
              },
              [48438] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["g"] = 0.31764706969261,
                      ["r"] = 1,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["xOffset"] = -3,
                  ["yOffset"] = 3,
              },
              [102342] = {
                  ["anyUnit"] = false,
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0,
                      ["g"] = 0.13333334028721,
                      ["r"] = 1,
                  },
                  ["cooldownAnchor"] = "CENTER",
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["displayText"] = false,
                  ["enabled"] = true,
                  ["id"] = 102342,
                  ["onlyShowMissing"] = false,
                  ["point"] = "TOPLEFT",
                  ["sizeOffset"] = 0,
                  ["style"] = "coloredIcon",
                  ["textThreshold"] = -1,
                  ["xOffset"] = 3,
                  ["yOffset"] = -3,
              },
              [102351] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0.90196084976196,
                      ["g"] = 0.90196084976196,
                      ["r"] = 0.1843137294054,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "TOPLEFT",
                  ["xOffset"] = 15,
                  ["yOffset"] = -3,
              },
              [102352] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0.90196084976196,
                      ["g"] = 0.90196084976196,
                      ["r"] = 0.1843137294054,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "TOPLEFT",
                  ["xOffset"] = 15,
                  ["yOffset"] = -3,
              },
              [155777] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 1,
                      ["g"] = 0.14901961386204,
                      ["r"] = 1,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "TOPRIGHT",
                  ["sizeOffset"] = 1,
                  ["xOffset"] = -15,
                  ["yOffset"] = 15,
              },
              [157982] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 1,
                      ["g"] = 1,
                      ["r"] = 1,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = -15,
                  ["yOffset"] = 3,
              },
              [188550] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0.13333334028721,
                      ["g"] = 0.9215686917305,
                      ["r"] = 0.39607846736908,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "LEFT",
                  ["xOffset"] = 3,
                  ["yOffset"] = -1,
              },
              [200389] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0.30588236451149,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "TOPLEFT",
                  ["xOffset"] = 15,
                  ["yOffset"] = -3,
              },
              [203554] = {
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["enabled"] = false,
              },
              [207386] = {
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["point"] = "RIGHT",
                  ["xOffset"] = -3,
                  ["yOffset"] = -1,
              },
              [383193] = {
                  ["anyUnit"] = false,
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 1,
                      ["g"] = 0.32941177487373,
                      ["r"] = 0,
                  },
                  ["cooldownAnchor"] = "CENTER",
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = 0,
                  ["countY"] = 0,
                  ["displayText"] = false,
                  ["enabled"] = true,
                  ["id"] = 383193,
                  ["onlyShowMissing"] = false,
                  ["point"] = "BOTTOMLEFT",
                  ["sizeOffset"] = 0,
                  ["style"] = "coloredIcon",
                  ["textThreshold"] = -1,
                  ["xOffset"] = 15,
                  ["yOffset"] = 3,
              },
              [391891] = {
                  ["color"] = {
                      ["a"] = 1,
                      ["b"] = 0.65098041296005,
                      ["g"] = 0.8117647767067,
                      ["r"] = 0.0039215688593686,
                  },
                  ["cooldownX"] = 0,
                  ["cooldownY"] = 0,
                  ["countAnchor"] = "CENTER",
                  ["countX"] = -13,
                  ["countY"] = -2,
                  ["point"] = "BOTTOMLEFT",
                  ["xOffset"] = 3,
                  ["yOffset"] = 3,
              },
          },
          ["EVOKER"] = {
              [360827] = {
                  ["countAnchor"] = "LEFT",
                  ["countX"] = -20,
                  ["countY"] = -1,
              },
              [410089] = {
                  ["point"] = "BOTTOM",
              },
          },
          ["PET"] = {
              [136] = {
                  ["style"] = "texturedIcon",
              },
              [193396] = {
                  ["style"] = "texturedIcon",
              },
              [272790] = {
                  ["style"] = "texturedIcon",
              },
          },
      },
  },
}::filters